const plants = [
    {
        id: 1,
        name: "Aloe Vera",
        img: "aloe_vera.jpg",
        description: "Planta suculenta conocida por sus propiedades curativas.",
        price: 150,
        stock: 20,
    },
    {
        id: 2,
        name: "Cactus San Pedro",
        img: "cactus_san_pedro.jpg",
        description: "Cactus de crecimiento rápido originario de los Andes.",
        price: 300,
        stock: 15,
    },
    {
        id: 3,
        name: "Helecho Boston",
        img: "helecho_boston.jpg",
        description: "Planta colgante con hojas frondosas y verdes.",
        price: 200,
        stock: 25,
    },
    {
        id: 4,
        name: "Orquídea Phalaenopsis",
        img: "orquidea_phalaenopsis.jpg",
        description: "Flor elegante y duradera, ideal para interiores.",
        price: 500,
        stock: 10,
    },
    {
        id: 5,
        name: "Bonsái Ficus",
        img: "bonsai_ficus.jpg",
        description: "Árbol miniatura perfecto para decorar espacios pequeños.",
        price: 750,
        stock: 8,
    },
    {
        id: 6,
        name: "Suculenta Echeveria",
        img: "echeveria.jpg",
        description: "Planta resistente de hojas carnosas y colores variados.",
        price: 100,
        stock: 30,
    },
    {
        id: 7,
        name: "Palma Areca",
        img: "palma_areca.jpg",
        description: "Planta tropical que purifica el aire de forma natural.",
        price: 400,
        stock: 12,
    },
    {
        id: 8,
        name: "Lavanda",
        img: "lavanda.jpg",
        description: "Hierba aromática conocida por su fragancia relajante.",
        price: 180,
        stock: 22,
    },
    {
        id: 9,
        name: "Menta",
        img: "menta.jpg",
        description: "Planta aromática perfecta para tés y cócteles.",
        price: 80,
        stock: 35,
    },
    {
        id: 10,
        name: "Hierba de Limón",
        img: "hierba_limon.jpg",
        description: "Planta cítrica ideal para infusiones y cocina.",
        price: 120,
        stock: 28,
    },
    {
        id: 11,
        name: "Calathea Orbifolia",
        img: "calathea_orbifolia.jpg",
        description: "Planta con hojas grandes y rayadas, de interior.",
        price: 350,
        stock: 10,
    },
    {
        id: 12,
        name: "Monstera Deliciosa",
        img: "monstera_deliciosa.jpg",
        description: "Planta exótica con hojas perforadas y gran tamaño.",
        price: 600,
        stock: 7,
    },
    {
        id: 13,
        name: "Potus",
        img: "potus.jpg",
        description: "Planta trepadora de fácil cuidado y gran belleza.",
        price: 130,
        stock: 25,
    },
    {
        id: 14,
        name: "Agave Azul",
        img: "agave_azul.jpg",
        description: "Planta suculenta conocida por ser base del tequila.",
        price: 200,
        stock: 18,
    },
    {
        id: 15,
        name: "Rosa Roja",
        img: "rosa_roja.jpg",
        description: "Flor clásica que simboliza el amor y la pasión.",
        price: 50,
        stock: 40,
    },
    {
        id: 16,
        name: "Clavel",
        img: "clavel.jpg",
        description: "Flor resistente y colorida, popular en jardines.",
        price: 70,
        stock: 32,
    },
    {
        id: 17,
        name: "Hiedra Inglesa",
        img: "hiedra_inglesa.jpg",
        description: "Planta trepadora ideal para cubrir muros.",
        price: 150,
        stock: 20,
    },
    {
        id: 18,
        name: "Crotón",
        img: "croton.jpg",
        description: "Planta de hojas multicolores y apariencia tropical.",
        price: 250,
        stock: 14,
    },
    {
        id: 19,
        name: "Geranio",
        img: "geranio.jpg",
        description: "Planta con flores vibrantes y fácil de cuidar.",
        price: 100,
        stock: 27,
    },
    {
        id: 20,
        name: "Hierbabuena",
        img: "hierbabuena.jpg",
        description: "Planta aromática utilizada en recetas y bebidas.",
        price: 90,
        stock: 30,
    },
    {
        id: 21,
        name: "Lirio de Paz",
        img: "lirio_paz.jpg",
        description: "Planta purificadora con elegantes flores blancas.",
        price: 300,
        stock: 16,
    },
    {
        id: 22,
        name: "Cactus Lápiz",
        img: "cactus_lapiz.jpg",
        description: "Planta suculenta de forma tubular y fácil cuidado.",
        price: 220,
        stock: 18,
    },
    {
        id: 23,
        name: "Dracaena",
        img: "dracaena.jpg",
        description: "Planta de interior con hojas largas y estrechas.",
        price: 280,
        stock: 12,
    },
    {
        id: 24,
        name: "Rábano Japonés",
        img: "rabano_japones.jpg",
        description: "Planta comestible conocida como Daikon.",
        price: 180,
        stock: 20,
    },
    {
        id: 25,
        name: "Jazmín",
        img: "jazmin.jpg",
        description: "Flor fragante utilizada en perfumería y té.",
        price: 150,
        stock: 22,
    },
    {
        id: 26,
        name: "Manzanilla",
        img: "manzanilla.jpg",
        description: "Hierba con propiedades relajantes y medicinales.",
        price: 100,
        stock: 26,
    },
    {
        id: 27,
        name: "Bambú de la Suerte",
        img: "bambu_suerte.jpg",
        description: "Planta asociada con la buena fortuna y prosperidad.",
        price: 180,
        stock: 19,
    },
    {
        id: 28,
        name: "Romero",
        img: "romero.jpg",
        description: "Hierba aromática ideal para cocinar y decorar.",
        price: 90,
        stock: 28,
    },
    {
        id: 29,
        name: "Cilantro",
        img: "cilantro.jpg",
        description: "Hierba versátil utilizada en cocina internacional.",
        price: 80,
        stock: 33,
    },
    {
        id: 30,
        name: "Tomillo",
        img: "tomillo.jpg",
        description: "Planta aromática con múltiples usos culinarios.",
        price: 85,
        stock: 30,
    },
];
