const plants = [
    {
        id: 1,
        name: "Aloe Vera",
        img: "./assets/img/aloe_vera.jpg",
        description: "Planta suculenta conocida por sus propiedades curativas.",
        price: 150,
        stock: 20,
    },
    {
        id: 2,
        name: "Cactus San Pedro",
        img: "./assets/img/cactus_san_pedro.jpg",
        description: "Cactus de crecimiento rápido originario de los Andes.",
        price: 300,
        stock: 15,
    },
    {
        id: 3,
        name: "Helecho Boston",
        img: "./assets/img/helecho_boston.jpg",
        description: "Planta colgante con hojas frondosas y verdes.",
        price: 200,
        stock: 25,
    },
    {
        id: 4,
        name: "Orquídea Phalaenopsis",
        img: "./assets/img/orquidea_phalaenopsis.jpg",
        description: "Flor elegante y duradera, ideal para interiores.",
        price: 500,
        stock: 10,
    },
    {
        id: 5,
        name: "Bonsái Ficus",
        img: "./assets/img/bonsai_ficus.jpg",
        description: "Árbol miniatura perfecto para decorar espacios pequeños.",
        price: 750,
        stock: 8,
    },
    {
        id: 6,
        name: "Suculenta Echeveria",
        img: "./assets/img/echeveria.jpg",
        description: "Planta resistente de hojas carnosas y colores variados.",
        price: 100,
        stock: 30,
    },
    {
        id: 7,
        name: "Palma Areca",
        img: "./assets/img/palma_areca.jpg",
        description: "Planta tropical que purifica el aire de forma natural.",
        price: 400,
        stock: 12,
    },
    {
        id: 8,
        name: "Lavanda",
        img: "./assets/img/lavanda.jpg",
        description: "Hierba aromática conocida por su fragancia relajante.",
        price: 180,
        stock: 22,
    },
    {
        id: 9,
        name: "Menta",
        img: "./assets/img/menta.jpg",
        description: "Planta aromática perfecta para tés y cócteles.",
        price: 80,
        stock: 35,
    },
    {
        id: 10,
        name: "Hierba de Limón",
        img: "./assets/img/hierba_limon.jpg",
        description: "Planta cítrica ideal para infusiones y cocina.",
        price: 120,
        stock: 28,
    },
    {
        id: 11,
        name: "Calathea Orbifolia",
        img: "./assets/img/calathea_orbifolia.jpg",
        description: "Planta con hojas grandes y rayadas, de interior.",
        price: 350,
        stock: 10,
    },
    {
        id: 12,
        name: "Monstera Deliciosa",
        img: "./assets/img/monstera_deliciosa.jpg",
        description: "Planta exótica con hojas perforadas y gran tamaño.",
        price: 600,
        stock: 7,
    },
    {
        id: 13,
        name: "Potus",
        img: "./assets/img/potus.jpg",
        description: "Planta trepadora de fácil cuidado y gran belleza.",
        price: 130,
        stock: 25,
    },
    {
        id: 14,
        name: "Agave Azul",
        img: "./assets/img/agave_azul.jpg",
        description: "Planta suculenta conocida por ser base del tequila.",
        price: 200,
        stock: 18,
    },
    {
        id: 15,
        name: "Rosa Roja",
        img: "./assets/img/rosa_roja.jpg",
        description: "Flor clásica que simboliza el amor y la pasión.",
        price: 50,
        stock: 40,
    },
    {
        id: 16,
        name: "Clavel",
        img: "./assets/img/clavel.jpg",
        description: "Flor resistente y colorida, popular en jardines.",
        price: 70,
        stock: 32,
    },
    {
        id: 17,
        name: "Hiedra Inglesa",
        img: "./assets/img/hiedra_inglesa.jpg",
        description: "Planta trepadora ideal para cubrir muros.",
        price: 150,
        stock: 20,
    },
    {
        id: 18,
        name: "Crotón",
        img: "./assets/img/croton.jpg",
        description: "Planta de hojas multicolores y apariencia tropical.",
        price: 250,
        stock: 14,
    },
    {
        id: 19,
        name: "Geranio",
        img: "./assets/img/geranio.jpg",
        description: "Planta con flores vibrantes y fácil de cuidar.",
        price: 100,
        stock: 27,
    },
    {
        id: 20,
        name: "Hierbabuena",
        img: "./assets/img/hierbabuena.jpg",
        description: "Planta aromática utilizada en recetas y bebidas.",
        price: 90,
        stock: 30,
    },
];
